[package]
name = "dustx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.46", features = ["derive"] }
tokio = { version = "1.47", features = ["rt-multi-thread","macros"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
humantime = "2.1"
thiserror = "2.0"
regex = "1.11"
dotenvy = "0.15"
walkdir = "2.5"
similar = { version = "2.7", default-features = false, features = ["text","inline"] }
tokio-postgres = { version = "0.7", features = ["runtime"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls","json"] }
parking_lot = "0.12.4"

postgresql_embedded = "0.19"
portpicker = "0.1"
zip = "4.5"
jiff = "0.2.15"

# Depend on the local Core library crate
dust = { path = "../core" }

[features]

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.10"
